#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Kotlin
kotlin.code.style=official
kotlin.jvm.target.validation.mode=warning

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2

suppressKotlinVersionCompatibilityCheck=true

kotlinCompilerExtensionVersion=
forcedKotlinVersion=2.3.10
forcedAndroidGradlePluginVersion=8.13.2
forcedComposeMultiplatformVersion=1.10.3

GRADLE_EXTENDED_VERSION_USED=6d42ea5

VOPENIA_MEET_TESTS_TUNNEL_ENDPOINT=
VOPENIA_MEET_TESTS_TUNNEL_API=
